#服务端口，随便起
server:
  port: 11011
#服务名称
spring:
  application:
    name: eurekaserver
  datasource:
    url: jdbc:mysql://cloud?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/
    register-with-eureka: false
    fetch-registry: false

