#服务端口，随便起
server:
  port: 8998
#服务名称
spring:
  application:
    name: userserver
  datasource:
    url: jdbc:mysql:///user?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11011/eureka/

